title: "Juan Zumaran Portfolio"
description: "Compliation of Data Visualization Projects realized during my MS DAV (data analytics and visualization) at Pratt Institute between 2024 and 2026"
theme: jekyll-theme-cayman
