title: "Juan Zumaran Portfolio"
description: "Compilation of Data Visualization Projects realized during my MS DAV (data analytics and visualization) at Pratt Institute between 2024 and 2026"
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
